<a href="https://colab.research.google.com/github/Garima0186/Data-Science-Methodologies/blob/main/Matix_Operation_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing  Numpy Libraray

In [1]:
import numpy as np

Matrix Addition

In [2]:
# two matrices can be added only if they have the same shape

# creating 2 matrices

In [3]:
a= np.array([[2,3],[4,5]])
b = np.array([[6,7],[8,9]])

print(a)
print(b)

[[2 3]
 [4 5]]
[[6 7]
 [8 9]]


In [5]:
a.shape

(2, 2)

In [6]:
b.shape

(2, 2)

Adding two matrices

In [7]:
sum = a+b
print(sum)

[[ 8 10]
 [12 14]]


In [9]:
# create 2 matrices with random values

matrix_1 = np.random.randint(10, size = (3,3))
matrix_2 = np.random.randint(20, size = (3,3))

print(matrix_1)
print(matrix_2)


[[5 7 9]
 [4 4 2]
 [9 2 8]]
[[18 17  2]
 [11  3  8]
 [ 3  4  3]]


In [10]:
sum = np.add(matrix_1, matrix_2)
print(sum)

[[23 24 11]
 [15  7 10]
 [12  6 11]]


In [11]:
matrix_3 = np.random.randint(10, size = (3,3))
matrix_4 = np.random.randint(20, size = (3,4))

print(matrix_1)
print(matrix_2)

sum_2 = np.add(matrix_3, matrix_4)
print(sum_2)

[[5 7 9]
 [4 4 2]
 [9 2 8]]
[[18 17  2]
 [11  3  8]
 [ 3  4  3]]


ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

We get this error because the shape of matrix_3 and matrix_4 are different

Matrix Subtraction

In [12]:
a= np.array([[2,3],[4,5]])
b = np.array([[6,7],[8,9]])

print(a)
print(b)

[[2 3]
 [4 5]]
[[6 7]
 [8 9]]


In [13]:
difference = a-b
print(difference)

[[-4 -4]
 [-4 -4]]


In [14]:
# create 2 matrices with random values

matrix_1 = np.random.randint(10, size = (3,3))
matrix_2 = np.random.randint(20, size = (3,3))

print(matrix_1)
print(matrix_2)


[[4 1 1]
 [7 2 7]
 [1 0 1]]
[[ 3  8  9]
 [16  1  1]
 [ 0 11  1]]


In [15]:
diff = np.subtract(matrix_1, matrix_2)
print(diff)

[[  1  -7  -8]
 [ -9   1   6]
 [  1 -11   0]]


Multiply a matrix by scalar

In [16]:
x= 5
y = np.random.randint(10, size = (4,4))

print(y)



[[8 4 2 0]
 [9 9 7 7]
 [2 3 5 8]
 [7 2 6 7]]


In [17]:
product = np.multiply(x,y)
print(product)

[[40 20 10  0]
 [45 45 35 35]
 [10 15 25 40]
 [35 10 30 35]]


Multiplying 2 Matrix

In [18]:
matrix_3 = np.random.randint(5, size = (3,3))
matrix_4 = np.random.randint(5, size = (3,4))



In [19]:
print(matrix_3)
print(matrix_4)

[[4 3 1]
 [4 3 0]
 [0 2 0]]
[[3 2 4 1]
 [3 0 2 1]
 [0 0 2 1]]


In [20]:
product = np.dot(matrix_3, matrix_4)
print(product)

[[21  8 24  8]
 [21  8 22  7]
 [ 6  0  4  2]]


In [21]:
product.shape

(3, 4)

In [24]:
matrix_3 = np.random.randint(5, size = (3,3))
matrix_4 = np.random.randint(5, size = (4,4))

In [25]:
product = np.dot(matrix_3, matrix_4)
print(product)

ValueError: shapes (3,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)

**Elementwise Matrix multiplication**

Both the matrix have same shape

In [26]:
matrix_3 = np.random.randint(5, size = (3,3))
matrix_4 = np.random.randint(5, size = (3,3))

In [27]:
print(matrix_3)

[[1 1 2]
 [3 0 0]
 [4 3 4]]


In [28]:
print(matrix_4)

[[3 4 1]
 [0 1 3]
 [2 3 3]]


In [29]:
product =np.multiply(matrix_3, matrix_4)
print(product)

[[ 3  4  2]
 [ 0  0  0]
 [ 8  9 12]]
