<a href="https://colab.research.google.com/github/Garima0186/Data-Science-Methodologies/blob/main/matix_basics_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


Creating a matrix using numpy

In [2]:
matrix_1 = np.array([[2,3],[6,7]])

In [3]:
print(matrix_1)

[[2 3]
 [6 7]]


In [4]:
matrix_1.shape

(2, 2)

In [5]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,90]])
print(matrix_2)
matrix_2.shape

[[10 35 45]
 [50 64 80]
 [20 15 90]]


(3, 3)

creating matrics with random values

In [6]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.64896084 0.68334037 0.69427305]
 [0.14979919 0.78709338 0.89745065]
 [0.81459456 0.27480819 0.98194786]]


In [9]:
random_integer_matrix = np.random.randint(100, size=(4,5))
print(random_integer_matrix)

[[92 82 78  7 74]
 [36 82 63 53  6]
 [35 51 40 70 63]
 [17 78 16 75 25]]


Matrix with all the values as 1

In [10]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
matrix_3 = np.ones((2,3),dtype= int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


Matrix will all the value as 0  / null matrix

In [12]:
null_matrix = np.zeros((4,4))
print(null_matrix )

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Identity matix

In [14]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
identity_matrix = np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Transpose of a matrix

In [17]:
# matrix with random numbers

a= np.random.randint(100, size=(4,5))
print(a)

[[ 7 53 81 32 19]
 [71 34 96 51 95]
 [52  6 91 84 53]
 [52 80 18 95 20]]


In [18]:
transpose_matrix = np.transpose(a)
print(transpose_matrix)

[[ 7 71 52 52]
 [53 34  6 80]
 [81 96 91 18]
 [32 51 84 95]
 [19 95 53 20]]
